import type { AmountGenerationMode, PaymentStatus, SavingPayment, SavingPlan, SavingSlot, SavingSlotStatus } from "@saving/shared";
import { getDemoBoard } from "@/lib/demo-store";

export interface PlanDraft { name: string; durationDays: number; generationMode: AmountGenerationMode; unitAmount: number; targetAmount: number; minAmount: number; maxAmount: number; stepAmount: number; customAmounts: number[]; startDate: string; timezone: string; confirmationMode: "PAYOS_ONLY" | "PAYOS_OR_MANUAL"; paymentExpiresInMinutes: number; }
const PLAN_KEY = "saving-100-flex-plan";

export function classicAmounts(days: number, unit: number): number[] { return Array.from({ length: days }, (_, index) => (index + 1) * unit); }
export function autoAmounts(days: number, target: number, min: number, max: number, step: number): number[] { let remaining = (target - days * min) / step; const capacity = (max - min) / step; return Array.from({ length: days }, () => { const units = Math.min(capacity, remaining); remaining -= units; return min + units * step; }); }
export function draftAmounts(draft: PlanDraft): number[] { if (draft.generationMode === "CLASSIC_SEQUENCE") return classicAmounts(draft.durationDays, draft.unitAmount); if (draft.generationMode === "CUSTOM_LIST") return draft.customAmounts; return autoAmounts(draft.durationDays, draft.targetAmount, draft.minAmount, draft.maxAmount, draft.stepAmount); }
export function planFromDraft(draft: PlanDraft): { plan: SavingPlan; slots: SavingSlot[] } { const amounts = draftAmounts(draft); const now = new Date().toISOString(); const id = crypto.randomUUID(); const target = amounts.reduce((sum, amount) => sum + amount, 0); const plan: SavingPlan = { id, userId: "demo-user", name: draft.name.trim(), durationDays: draft.durationDays, currentDayIndex: 1, completedDays: 0, generationMode: draft.generationMode, targetAmount: target, totalSavedAmount: 0, remainingAmount: target, unitAmount: draft.generationMode === "CLASSIC_SEQUENCE" ? draft.unitAmount : null, minAmount: Math.min(...amounts), maxAmount: Math.max(...amounts), stepAmount: draft.stepAmount || null, progressMode: "FLEXIBLE_CONTRIBUTION_DAYS", confirmationMode: draft.confirmationMode, paymentDestinationMode: "SINGLE_OWNER_CHANNEL", paymentExpiresInMinutes: draft.paymentExpiresInMinutes, timezone: draft.timezone, startDate: draft.startDate, status: "ACTIVE", createdAt: now, activatedAt: now, completedAt: null }; const slots = amounts.map((amount, index) => ({ id: `${id}-slot-${index + 1}`, userId: "demo-user", planId: id, slotIndex: index + 1, amount, status: "AVAILABLE" as SavingSlotStatus, reservedByPaymentId: null, reservationExpiresAt: null, assignedDayIndex: null, paidPaymentId: null, completedAt: null })); return { plan, slots }; }
export function saveDemoPlan(value: { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] }): void { if (typeof window !== "undefined") window.localStorage.setItem(PLAN_KEY, JSON.stringify(value)); }
export function getDemoPlan(): { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] } { if (typeof window !== "undefined") { const value = window.localStorage.getItem(PLAN_KEY); if (value) return JSON.parse(value) as { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] }; } const board = getDemoBoard(); const amounts = board.cells.map((cell) => cell.amount); const now = new Date().toISOString(); const plan: SavingPlan = { id: "demo-plan", userId: "demo-user", name: "Quỹ linh hoạt 100 ngày", durationDays: 100, currentDayIndex: 13, completedDays: 12, generationMode: "CLASSIC_SEQUENCE", targetAmount: 5050000, totalSavedAmount: 820000, remainingAmount: 4230000, unitAmount: 1000, minAmount: 1000, maxAmount: 100000, stepAmount: 1000, progressMode: "FLEXIBLE_CONTRIBUTION_DAYS", confirmationMode: "PAYOS_ONLY", paymentDestinationMode: "SINGLE_OWNER_CHANNEL", paymentExpiresInMinutes: 15, timezone: "Asia/Ho_Chi_Minh", startDate: "2026-07-15", status: "ACTIVE", createdAt: now, activatedAt: now, completedAt: null }; const slots = amounts.map((amount, index) => ({ id: `demo-plan-slot-${index + 1}`, userId: "demo-user", planId: plan.id, slotIndex: index + 1, amount, status: index < 12 ? "PAID" as SavingSlotStatus : "AVAILABLE" as SavingSlotStatus, reservedByPaymentId: null, reservationExpiresAt: null, assignedDayIndex: index < 12 ? index + 1 : null, paidPaymentId: null, completedAt: index < 12 ? now : null })); return { plan, slots, payments: [] }; }
export function createDemoPayment(state: { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] }, slotId: string): { state: typeof state; payment: SavingPayment } { const slot = state.slots.find((item) => item.id === slotId); if (!slot || slot.status !== "AVAILABLE") throw new Error("Khoản tiền này không còn khả dụng."); const pending = state.payments.find((item) => item.planId === state.plan.id && item.dayIndex === state.plan.currentDayIndex && ["CREATING", "PENDING", "PROCESSING"].includes(item.status)); if (pending) throw new Error("Bạn đang có một khoản chờ thanh toán trong ngày này."); const now = new Date(); const payment: SavingPayment = { id: crypto.randomUUID(), userId: state.plan.userId, planId: state.plan.id, slotId, dayIndex: state.plan.currentDayIndex, provider: "PAYOS", orderCode: 900000001 + state.payments.length, paymentLinkId: `mock-${slotId}`, amount: slot.amount, currency: "VND", description: `TK${900000001 + state.payments.length}`, checkoutUrl: `/payment/return?paymentId=${slotId}`, qrCode: `mock-payos:${slot.amount}`, status: "PENDING", idempotencyKey: crypto.randomUUID(), expiresAt: new Date(now.getTime() + state.plan.paymentExpiresInMinutes * 60000).toISOString(), paidAt: null, cancelledAt: null, lastReconciledAt: null, errorCode: null, errorMessage: null, createdAt: now.toISOString() }; slot.status = "RESERVED"; slot.reservedByPaymentId = payment.id; slot.reservationExpiresAt = payment.expiresAt; const next = { ...state, payments: [...state.payments, payment] }; saveDemoPlan(next); return { state: next, payment }; }
export function markDemoPaymentPaid(state: { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] }, paymentId: string): typeof state { const payment = state.payments.find((item) => item.id === paymentId); if (!payment) throw new Error("Không tìm thấy thanh toán."); if (payment.status === "PAID") return state; const slot = state.slots.find((item) => item.id === payment.slotId); if (!slot || slot.status !== "RESERVED") throw new Error("Slot không còn được giữ."); const now = new Date().toISOString(); payment.status = "PAID"; payment.paidAt = now; slot.status = "PAID"; slot.paidPaymentId = payment.id; slot.assignedDayIndex = payment.dayIndex; slot.reservedByPaymentId = null; slot.reservationExpiresAt = null; slot.completedAt = now; state.plan.completedDays += 1; state.plan.currentDayIndex = Math.min(state.plan.completedDays + 1, state.plan.durationDays); state.plan.totalSavedAmount += payment.amount; state.plan.remainingAmount -= payment.amount; if (state.plan.completedDays >= state.plan.durationDays) { state.plan.status = "COMPLETED"; state.plan.completedAt = now; } saveDemoPlan(state); return state; }
export function cancelDemoPayment(state: { plan: SavingPlan; slots: SavingSlot[]; payments: SavingPayment[] }, paymentId: string): typeof state { const payment = state.payments.find((item) => item.id === paymentId); if (!payment || payment.status === "PAID") return state; const slot = state.slots.find((item) => item.id === payment.slotId); if (slot && slot.status === "RESERVED") { slot.status = "AVAILABLE"; slot.reservedByPaymentId = null; slot.reservationExpiresAt = null; } payment.status = "CANCELLED"; payment.cancelledAt = new Date().toISOString(); saveDemoPlan(state); return state; }
export function filterSlots(slots: SavingSlot[], status: "ALL" | SavingSlotStatus): SavingSlot[] { return status === "ALL" ? slots : slots.filter((slot) => slot.status === status); }
export function paymentStatusLabel(status: PaymentStatus): string { return ({ CREATING: "Đang tạo", PENDING: "Đang chờ", PROCESSING: "Đang xác minh", PAID: "Đã thanh toán", CANCELLED: "Đã hủy", EXPIRED: "Đã hết hạn", FAILED: "Thất bại" } as Record<PaymentStatus, string>)[status]; }
