import { Injectable } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { ApiError } from "../common/api-error";
import { currentStreak, localDate } from "../common/date";
import type { BoardCell, BoardResponse, Checkin, ChallengeSummary } from "@saving/shared";

interface Challenge { id: string; userId: string; name: string; unitAmount: number; targetAmount: number; savedAmount: number; completedCells: number; status: "ACTIVE" | "COMPLETED" | "ARCHIVED"; startDate: string; }

@Injectable()
export class ChallengesService {
  private readonly challenges = new Map<string, Challenge>();
  private readonly checkins = new Map<string, Checkin>();
  private readonly demoUser = "demo-user";

  constructor() { this.seed(); }

  private seed(): void {
    const challenge: Challenge = { id: "demo-challenge", userId: this.demoUser, name: "Thử thách tiết kiệm 100 ngày", unitAmount: 1000, targetAmount: 5050000, savedAmount: 1250000, completedCells: 24, status: "ACTIVE", startDate: "2026-07-01" };
    this.challenges.set(challenge.id, challenge);
    for (let number = 1; number <= 24; number += 1) this.checkins.set(`demo-${number}`, { id: `demo-${number}`, number, amount: number * 1000, localDate: `2026-07-${String(number).padStart(2, "0")}`, status: "COMPLETED", createdAt: new Date(2026, 6, number, 9, 15).toISOString() });
  }
  private owned(id: string, userId: string): Challenge { const item = this.challenges.get(id); if (!item || item.userId !== userId) throw new ApiError("CHALLENGE_NOT_FOUND", "Không tìm thấy thử thách.", 404); return item; }
  private summary(item: Challenge): ChallengeSummary { const completed = [...this.checkins.values()].filter((checkin) => checkin.status === "COMPLETED"); return { id: item.id, name: item.name, savedAmount: item.savedAmount, targetAmount: item.targetAmount, completedCells: item.completedCells, totalCells: 100, progressPercent: Number(((item.savedAmount / item.targetAmount) * 100).toFixed(2)), remainingAmount: Math.max(item.targetAmount - item.savedAmount, 0), status: item.status, streak: currentStreak(completed.map((checkin) => checkin.localDate)) }; }
  board(userId = this.demoUser, id = "demo-challenge"): BoardResponse { const challenge = this.owned(id, userId); const byNumber = new Map([...this.checkins.values()].filter((checkin) => checkin.status === "COMPLETED").map((checkin) => [checkin.number, checkin])); const cells: BoardCell[] = Array.from({ length: 100 }, (_, index) => { const number = index + 1; const checkin = byNumber.get(number); return { number, amount: number * challenge.unitAmount, status: checkin ? "COMPLETED" : "AVAILABLE", completedDate: checkin?.localDate ?? null }; }); const today = localDate(process.env.DEFAULT_TIMEZONE ?? "Asia/Ho_Chi_Minh"); const todayCheckin = [...this.checkins.values()].find((checkin) => checkin.localDate === today && checkin.status === "COMPLETED") ?? null; return { challenge: this.summary(challenge), cells, today: { localDate: today, checked: Boolean(todayCheckin), checkin: todayCheckin } }; }
  create(userId = this.demoUser, name = "Thử thách tiết kiệm 100 ngày"): BoardResponse { const challenge: Challenge = { id: randomUUID(), userId, name, unitAmount: 1000, targetAmount: 5050000, savedAmount: 0, completedCells: 0, status: "ACTIVE", startDate: localDate("Asia/Ho_Chi_Minh") }; this.challenges.set(challenge.id, challenge); return this.board(userId, challenge.id); }
  list(userId = this.demoUser): ChallengeSummary[] { return [...this.challenges.values()].filter((item) => item.userId === userId).map((item) => this.summary(item)); }
  checkIn(userId: string, challengeId: string, number: number, idempotencyKey: string): BoardResponse { const challenge = this.owned(challengeId, userId); if (challenge.status !== "ACTIVE") throw new ApiError("CHALLENGE_NOT_ACTIVE", "Thử thách này không còn hoạt động."); if (!Number.isInteger(number) || number < 1 || number > 100) throw new ApiError("CELL_INVALID", "Ô tiết kiệm không hợp lệ."); const duplicateKey = [...this.checkins.values()].find((checkin) => checkin.id === idempotencyKey || (checkin.number === number && checkin.status === "COMPLETED")); if (duplicateKey) { if (duplicateKey.id === idempotencyKey) return this.board(userId, challengeId); throw new ApiError("CELL_ALREADY_COMPLETED", `Ô số ${number} đã được hoàn thành.`, 409); } const today = localDate(process.env.DEFAULT_TIMEZONE ?? "Asia/Ho_Chi_Minh"); if ([...this.checkins.values()].some((checkin) => checkin.localDate === today && checkin.status === "COMPLETED")) throw new ApiError("DAILY_LIMIT_REACHED", "Hôm nay bạn đã tiết kiệm rồi.", 409); const checkin: Checkin = { id: idempotencyKey || randomUUID(), number, amount: number * challenge.unitAmount, localDate: today, status: "COMPLETED", createdAt: new Date().toISOString() }; this.checkins.set(checkin.id, checkin); challenge.savedAmount += checkin.amount; challenge.completedCells += 1; if (challenge.completedCells === 100) challenge.status = "COMPLETED"; return this.board(userId, challengeId); }
  reverse(userId: string, checkinId: string): BoardResponse { const checkin = this.checkins.get(checkinId); if (!checkin || checkin.status !== "COMPLETED") throw new ApiError("CHECKIN_NOT_FOUND", "Không tìm thấy khoản tiết kiệm có thể hoàn tác.", 404); const challenge = [...this.challenges.values()].find((item) => item.userId === userId && [...this.checkins.values()].some((entry) => entry.id === checkinId)); if (!challenge) throw new ApiError("CHECKIN_NOT_FOUND", "Không tìm thấy khoản tiết kiệm.", 404); checkin.status = "REVERSED"; checkin.reversedAt = new Date().toISOString(); challenge.savedAmount -= checkin.amount; challenge.completedCells -= 1; if (challenge.status === "COMPLETED") challenge.status = "ACTIVE"; return this.board(userId, challenge.id); }
  history(userId: string, challengeId: string): Checkin[] { this.owned(challengeId, userId); return [...this.checkins.values()].filter((checkin) => checkin.status === "COMPLETED" || checkin.status === "REVERSED").sort((a, b) => b.createdAt.localeCompare(a.createdAt)); }
  statistics(userId: string, challengeId: string) { const challenge = this.owned(challengeId, userId); const items = [...this.checkins.values()].filter((checkin) => checkin.status === "COMPLETED"); const amounts = items.map((checkin) => checkin.amount); return { totalSaved: challenge.savedAmount, targetAmount: challenge.targetAmount, progressPercent: this.summary(challenge).progressPercent, completedCells: challenge.completedCells, remainingCells: 100 - challenge.completedCells, averagePerDay: items.length ? Math.round(challenge.savedAmount / items.length) : 0, largestAmount: amounts.length ? Math.max(...amounts) : 0, smallestAmount: amounts.length ? Math.min(...amounts) : 0, currentStreak: this.summary(challenge).streak, bestStreak: this.summary(challenge).streak, startDate: challenge.startDate, expectedCompletionDate: null }; }
  random(userId: string, challengeId: string): { number: number; amount: number } { const board = this.board(userId, challengeId); const available = board.cells.filter((cell) => cell.status === "AVAILABLE"); if (!available.length) throw new ApiError("CHALLENGE_COMPLETED", "Bạn đã hoàn thành toàn bộ thử thách."); const pick = available[Math.floor(Math.random() * available.length)]; return { number: pick.number, amount: pick.amount }; }
}
